Config:
  Organisation: "Paulina Cajiao"
  SourceEnvName: "Sandbox"
  SourceServerName: "Sandbox"
  SourceServerType: "SERVER"
  TargetEnvName: "Production"
  TargetServerName: "Production"
  TargetServerType: "SERVER"
  TargetClientId: "7cd2e723954c47a0b9c9de101907e188"
  TargetClientSecret: "B12ecbc991Ee4797b71285C225259329"
  Applications:
    - appName: "http-proxy-v1"
      apiInstanceId: 16748960
      proxyurl: http://newurlproxy.com
    #- appName: "usersapi"
    #  apiInstanceId: 322618
    #  proxyurl: http://newurlproxy.com

