Config:
  Organisation: "Paulina Cajiao"
  SourceEnvName: "Sandbox"
  SourceServerName: "sandbox"
  SourceServerType: "CH"
  TargetEnvName: "Production"
  TargetServerName: "production"
  TargetServerType: "CH"
  Applications:
    - appName: "http-proxy-v1-api-gateway"
      apiInstanceId: 16748960
      proxyurl: http://newurlproxy.com
    #- appName: "usersapi"
    #  apiInstanceId: 322618
    #  proxyurl: http://newurlproxy.com
